services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5555:5555"
    expose:
      - "8000"
      - "5555"
    volumes:
      - .:/app
    env_file:
      - .env  
    depends_on:
      - redis    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
