services:
  app:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file:
      - .env  
    depends_on:
      - redis-stack    
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    command: redis-stack-server --maxmemory 1500mb --maxmemory-policy volatile-lru --maxclients 10000
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"
    environment:
      - RI_APP_PORT=8001
    volumes:
      - redis-insight:/data

volumes:
  redis-data:
  redis-insight:
