services:
  app:
    container_name: zavmo_app
    build: .
    ports:
      - "8000:8000"
      - "5555:5555"
    expose:
      - "8000"
      - "5555"
    volumes:
      - .:/app
    env_file:
      - .env  
    restart: unless-stopped
    networks:
      - zavmonetwork

networks:
  zavmonetwork:
    external: true

    
