# Generated by Django 5.1.1 on 2024-10-13 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "org_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("org_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliverStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modules", models.JSONField(default=list, verbose_name="Modules")),
                (
                    "timeline",
                    models.TextField(blank=True, null=True, verbose_name="Timeline"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliver_stage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemonstrateStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_module",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Current Module",
                    ),
                ),
                (
                    "completed_modules",
                    models.JSONField(default=list, verbose_name="Completed Modules"),
                ),
                (
                    "understanding_level",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Understanding Level",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demonstrate_stage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoverStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_goals",
                    models.JSONField(default=list, verbose_name="Learning Goals"),
                ),
                (
                    "learning_goal_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Learning Goal Rationale"
                    ),
                ),
                (
                    "knowledge_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Beginner"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                        ],
                        null=True,
                        verbose_name="Knowledge Level",
                    ),
                ),
                (
                    "application_area",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Area"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_stage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscussStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_objective",
                    models.TextField(
                        blank=True, null=True, verbose_name="Learning Objective"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discuss_stage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearnerJourney",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="learner_journey",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "profile"),
                            (2, "discover"),
                            (3, "discuss"),
                            (4, "deliver"),
                            (5, "demonstrate"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learner_journeys",
                        to="stage_app.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "edu_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Primary School"),
                            (2, "Middle School"),
                            (3, "High School"),
                            (4, "Associate Degree"),
                            (5, "Bachelor's Degree"),
                            (6, "Master's Degree"),
                            (7, "PhD"),
                        ],
                        null=True,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "current_role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current Role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_stage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
