# Generated by Django 5.1.1 on 2024-10-25 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "org_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("org_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FourDSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "discover"),
                            (2, "discuss"),
                            (3, "deliver"),
                            (4, "demonstrate"),
                            (5, "completed"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="four_d_sequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscussStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_areas",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Interest Areas"
                    ),
                ),
                (
                    "learning_style",
                    models.TextField(
                        blank=True, null=True, verbose_name="Learning Style"
                    ),
                ),
                (
                    "available_time",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Available Time (hours per week)",
                    ),
                ),
                (
                    "curriculum",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Curriculum Plan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discuss_stage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discuss_stage",
                        to="stage_app.fourdsequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoverStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_goals",
                    models.TextField(
                        blank=True, null=True, verbose_name="Learning Goals"
                    ),
                ),
                (
                    "learning_goal_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Learning Goal Rationale"
                    ),
                ),
                (
                    "knowledge_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Beginner"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                        ],
                        null=True,
                        verbose_name="Knowledge Level",
                    ),
                ),
                (
                    "application_area",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Area"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_stage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_stage",
                        to="stage_app.fourdsequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemonstrateStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluations",
                    models.JSONField(blank=True, null=True, verbose_name="Evaluations"),
                ),
                (
                    "understanding_levels",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Beginner"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                        ],
                        null=True,
                        verbose_name="Understanding Level",
                    ),
                ),
                (
                    "feedback_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="Feedback Summary"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demonstrate_stage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demonstrate_stage",
                        to="stage_app.fourdsequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lessons",
                    models.JSONField(blank=True, null=True, verbose_name="Lessons"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliver_stage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliver_stage",
                        to="stage_app.fourdsequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "edu_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Primary School"),
                            (2, "Middle School"),
                            (3, "High School"),
                            (4, "Associate Degree"),
                            (5, "Bachelor's Degree"),
                            (6, "Master's Degree"),
                            (7, "PhD"),
                        ],
                        null=True,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "current_role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current Role",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stage_app.org",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_stage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
