# Generated by Django 5.1.1 on 2024-10-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverstage',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demonstratestage',
            name='current_module',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demonstratestage',
            name='understanding_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discussstage',
            name='content_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discussstage',
            name='pacing_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discussstage',
            name='structure_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='edu_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primary School'), (2, 'Middle School'), (3, 'High School'), (4, 'Associate Degree'), (5, "Bachelor's Degree"), (6, "Master's Degree"), (7, 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
