# Generated by Django 5.1.1 on 2024-10-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverstage',
            name='modules',
            field=models.JSONField(default=list, verbose_name='Modules'),
        ),
        migrations.AlterField(
            model_name='deliverstage',
            name='timeline',
            field=models.TextField(blank=True, null=True, verbose_name='Timeline'),
        ),
        migrations.AlterField(
            model_name='deliverstage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_stage', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='demonstratestage',
            name='completed_modules',
            field=models.JSONField(default=list, verbose_name='Completed Modules'),
        ),
        migrations.AlterField(
            model_name='demonstratestage',
            name='current_module',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Module'),
        ),
        migrations.AlterField(
            model_name='demonstratestage',
            name='understanding_level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Understanding Level'),
        ),
        migrations.AlterField(
            model_name='demonstratestage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demonstrate_stage', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='discoverstage',
            name='application_area',
            field=models.TextField(blank=True, null=True, verbose_name='Application Area'),
        ),
        migrations.AlterField(
            model_name='discoverstage',
            name='knowledge_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], null=True, verbose_name='Knowledge Level'),
        ),
        migrations.AlterField(
            model_name='discoverstage',
            name='learning_goal_rationale',
            field=models.TextField(blank=True, null=True, verbose_name='Learning Goal Rationale'),
        ),
        migrations.AlterField(
            model_name='discoverstage',
            name='learning_goals',
            field=models.JSONField(default=list, verbose_name='Learning Goals'),
        ),
        migrations.AlterField(
            model_name='discoverstage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discover_stage', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='discussstage',
            name='learning_objective',
            field=models.TextField(blank=True, null=True, verbose_name='Learning Objective'),
        ),
        migrations.AlterField(
            model_name='discussstage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discuss_stage', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='current_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Role'),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='edu_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primary School'), (2, 'Middle School'), (3, 'High School'), (4, 'Associate Degree'), (5, "Bachelor's Degree"), (6, "Master's Degree"), (7, 'PhD')], null=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profilestage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stage', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
